version: '3.7'

services:
  am.services.portfolio.host:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "80"
  postgresql:
    image: postgres:13
    container_name: postgresql
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
       - ${DB_DATA}:/var/lib/postgresql/data
       - .volumes/db/data:${DB_DATA}
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${MQ_PASSWORD}
    volumes:
      - ${MQ_DATA}:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq
      - ${MQ_LOG}:/var/log/rabbitmq/log
