version: '3.4'

services:
  am.services.portfolio.host:
    image: ${DOCKER_REGISTRY-}amservicesportfoliohost:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: services/.net/Portfolio/Host/Dockerfile
